export const DEFAULT_EMAIL_TEMPLATES = [
  { id:'security-deposit-review', name:'Security deposit review', audience:'Owner', schedule:'The morning after checkout', trigger:'scheduled_security_deposit_review', exception:'Only for bookings with a refundable security deposit; document deductions before issuing a partial refund.', subject:'Review {{guestName}} security deposit', body:'{{guestName}} checked out after the {{arrival}}–{{departure}} stay. Review the property and refund the {{securityDeposit}} security deposit through the Command Center if no deductions are needed. Document and itemize any deduction.\n\nOpen: {{adminUrl}}', enabled:true, system:true },
  { id:'request-received', name:'Checkout started', audience:'Guest', schedule:'Immediately after direct checkout begins', trigger:'request_submitted', exception:'Normally replaced by the automatic checkout email.', subject:'Your Weeks Creek Haven checkout is ready', body:'Hi {{guestName}},\n\nYour private checkout packet is ready. Your selected dates remain available to other guests until the required deposit is received; the first completed deposit secures them.\n\nOpen the packet from your email to review the invoice and sign the agreement.', enabled:true, system:true },
  { id:'owner-new-request', name:'New checkout owner alert', audience:'Owner', schedule:'Immediately after direct checkout begins', trigger:'request_submitted_owner', exception:'Only sends when OWNER_EMAIL is configured.', subject:'New cabin checkout from {{guestName}}', body:'{{guestName}} started checkout. Review the dates, pricing, guest details, deposit status, and notes in the Command Center: {{adminUrl}}', enabled:true, system:true },
  { id:'booking-approved', name:'Invoice & booking packet', audience:'Guest', schedule:'Immediately after available dates are submitted', trigger:'booking_approved', exception:'Complimentary and Friends & Family stays receive their applicable payment wording.', subject:'Complete your Weeks Creek Haven booking', body:'Hi {{guestName}},\n\nYour checkout for {{arrival}} through {{departure}} is ready. Total due is {{total}}. {{paymentText}}\n\nOpen your private booking packet: {{packetUrl}}\n\nThe dates remain open until the required deposit is received. Check-in begins at 4:00 PM and checkout is {{checkout}}.', enabled:true, system:true },
  { id:'booking-packet', name:'Agreement and booking packet reminder', audience:'Guest', schedule:'When owner selects Send packet', trigger:'packet_requested', exception:'Wording changes when payment or signature is already complete.', subject:'Please sign your Weeks Creek Haven agreement', body:'Hi {{guestName}},\n\n{{nextStep}}\n\nStay: {{arrival}} through {{departure}}\n\nOpen your private booking packet: {{packetUrl}}\n\nCheck-in begins at 4:00 PM. Checkout is {{checkout}}.', enabled:true, system:true },
  { id:'payment-received', name:'Payment received—agreement needed', audience:'Guest', schedule:'Automatically after required payment is detected', trigger:'payment_requirement_met', exception:'Only sends when the agreement has not yet been signed.', subject:'Payment received — finish your Weeks Creek Haven booking', body:'Hi {{guestName}},\n\nWe received your required payment for {{arrival}} through {{departure}}. Your dates are reserved.\n\nOpen your private booking packet to sign the rental agreement: {{packetUrl}}\n\nOnce the agreement is signed, your stay will be marked Booked automatically.', enabled:true, system:true },
  { id:'booking-confirmed', name:'Booked welcome packet', audience:'Guest', schedule:'Automatically after payment and agreement are complete', trigger:'booking_finalized', exception:'Complimentary stays require the agreement only.', subject:'You’re booked at Weeks Creek Haven', body:'Hi {{guestName}},\n\nYou’re officially booked for {{arrival}} through {{departure}}. Check-in begins at 4:00 PM and checkout is {{checkout}}.\n\nYour private welcome packet contains your signed agreement, booking summary, and cabin information: {{packetUrl}}\n\nWe’re excited to welcome you to the Haven!', enabled:true, system:true },
  { id:'guest-invitation', name:'Guest Guide invitation', audience:'Guest', schedule:'When owner emails a Guest Access invitation', trigger:'invite_sent', exception:'Stay choices and deadlines appear only when attached to the invitation.', subject:'Your Weeks Creek Haven invitation', body:'Hi {{guestName}},\n\nYou’re invited to the Weeks Creek Guest Guide.\n\nOpen: {{hubUrl}}\nYour code: {{inviteCode}}', enabled:true, system:true },
  { id:'stay-selected', name:'Guest selected offered dates', audience:'Guest', schedule:'Immediately after an invited guest chooses dates', trigger:'stay_selected', exception:'Complimentary and paid offers receive different price wording.', subject:'Your Weeks Creek Haven stay choice is reserved', body:'Hi {{guestName}},\n\nYou chose {{arrival}} through {{departure}}. We released the other offered dates.\n\nOpen your private booking packet: {{packetUrl}}', enabled:true, system:true },
  { id:'reservation-cancelled', name:'Reservation cancellation', audience:'Guest', schedule:'Immediately when owner cancels a reservation', trigger:'booking_cancelled', exception:'Refund details are sent separately after Square processes a refund.', subject:'Your Weeks Creek Haven reservation was cancelled', body:'Hi {{guestName}},\n\nYour Weeks Creek Haven reservation from {{arrival}} through {{departure}} has been cancelled. Those dates are no longer being held. If this was unexpected, reply and we will help.', enabled:true, system:true },
  { id:'request-declined', name:'Date request declined', audience:'Guest', schedule:'Immediately when owner declines a request', trigger:'request_declined', exception:'Use when neither requested date can be approved.', subject:'Your Weeks Creek Haven date request', body:'Hi {{guestName}},\n\nThanks for checking with us. We can’t make either requested date work this time, but we’d love for you to try another weekend.', enabled:true, system:true },
  { id:'refund-issued', name:'Refund confirmation', audience:'Guest', schedule:'Immediately after Square accepts a refund', trigger:'refund_issued', exception:'Only sends when the booking has a guest email address.', subject:'A Weeks Creek Haven refund was issued', body:'Hi {{guestName}},\n\nWe issued a {{refundAmount}} refund through Square. Reason: {{refundReason}}.\n\nSquare will return the funds to the original payment method. Processing time depends on the bank or card issuer.', enabled:true, system:true },
  { id:'review-request', name:'Post-stay review request', audience:'Guest', schedule:'When owner selects Send review request', trigger:'review_requested', exception:'Available after a completed stay; private comments are never published without permission.', subject:'How was your Weeks Creek Haven stay?', body:'Hi {{guestName}},\n\nThank you for staying at Weeks Creek Haven. We would love to hear what you enjoyed and anything we can improve.\n\nLeave your rating and review: {{reviewUrl}}', enabled:true, system:true },
  { id:'deposit-reminder', name:'Deposit due reminder', audience:'Guest', schedule:'Before the applicable deposit deadline when deposit is unpaid', trigger:'scheduled_deposit_reminder', exception:'Skip complimentary, fully paid, and stays started within seven days.', subject:'Your Weeks Creek Haven deposit is due soon', body:'Hi {{guestName}},\n\nA friendly reminder that your 20% deposit of {{depositAmount}} is is due by the deadline shown on your invoice to keep {{arrival}} through {{departure}} reserved.\n\nPay through your Square invoice: {{paymentUrl}}', enabled:true, system:true },
  { id:'deposit-grace', name:'Deposit grace-period notice', audience:'Guest', schedule:'When deposit is overdue; starts the 24-hour grace period', trigger:'scheduled_deposit_overdue', exception:'Skip when payment has arrived or owner has documented a written exception.', subject:'Action needed to keep your Weeks Creek Haven dates', body:'Hi {{guestName}},\n\nWe have not received the reservation deposit for {{arrival}} through {{departure}}. Your 24-hour grace period has started. If payment is still missing after that period, the dates may be released.\n\nPay here: {{paymentUrl}}', enabled:true, system:true },
  { id:'early-bird-expired', name:'Early Bird price expired', audience:'Guest', schedule:'Seven days after checkout begins when either the deposit or signature is missing', trigger:'scheduled_early_bird_expired', exception:'Skip when both the required deposit and rental agreement are complete.', subject:'Your Early Bird price has expired', body:'Hi {{guestName}},\n\nThe seven-day window to complete the deposit and rental agreement for {{arrival}} through {{departure}} has ended. The discounted invoice is no longer active. To stay with us, please choose dates again so we can price a new request at the current rate.\n\nRebook here: {{bookingUrl}}', enabled:true, system:true },
  { id:'balance-reminder', name:'Remaining balance reminder', audience:'Guest', schedule:'One day before the balance due date', trigger:'scheduled_balance_reminder', exception:'Skip paid-in-full, complimentary, and stays booked within seven days.', subject:'Your Weeks Creek Haven balance is due tomorrow', body:'Hi {{guestName}},\n\nYour remaining balance of {{balanceAmount}} for {{arrival}} through {{departure}} is due tomorrow.\n\nPay through your Square invoice: {{paymentUrl}}', enabled:true, system:true },
  { id:'balance-grace', name:'Balance grace-period notice', audience:'Guest', schedule:'When the seven-day balance is overdue', trigger:'scheduled_balance_overdue', exception:'Skip when paid or owner has documented a written exception.', subject:'Action needed on your Weeks Creek Haven balance', body:'Hi {{guestName}},\n\nYour remaining balance for {{arrival}} through {{departure}} is overdue. This begins the 24-hour grace period. If payment remains unpaid, the dates may be released.\n\nPay here: {{paymentUrl}}', enabled:true, system:true },
  { id:'pre-arrival-guide', name:'Pre-arrival guide', audience:'Guest', schedule:'Three days before check-in at 9:00 AM Eastern', trigger:'scheduled_before_arrival', exception:'Only for Booked stays; skip cancelled reservations.', subject:'Everything you need for Weeks Creek Haven', body:'Hi {{guestName}},\n\nYour stay begins in three days. Review your arrival directions, parking, Wi-Fi, cabin guide, and Fannin County guest notice here: {{packetUrl}}\n\nCheck-in begins at 4:00 PM on {{arrival}}. Checkout is {{checkout}}.', enabled:true, system:true },
  { id:'checkin-reminder', name:'Check-in day reminder', audience:'Guest', schedule:'Check-in day at 9:00 AM Eastern', trigger:'scheduled_checkin_day', exception:'Only for Booked stays; skip cancelled reservations.', subject:'Today is check-in day at Weeks Creek Haven', body:'Hi {{guestName}},\n\nToday is check-in day! Entry begins at 4:00 PM. Your directions, access details, parking information, and cabin guide are in your private packet: {{packetUrl}}\n\nSafe travels to Blue Ridge.', enabled:true, system:true },
  { id:'midstay-rebook', name:'Mid-stay rebooking reminder', audience:'Guest', schedule:'Halfway through the stay', trigger:'scheduled_midstay', exception:'Only for Booked stays; sends once. One promotional discount per future stay.', subject:'Want another Haven stay?', body:'Hi {{guestName}},\n\nWe hope you are enjoying Weeks Creek Haven. Book your next eligible stay before checkout to receive the 15% rebook offer. Use your return and referral code: {{referralCode}}\n\nOne promotional discount applies per stay, and the best eligible offer will be used.\n\nChoose your next dates: {{bookingUrl}}', enabled:true, system:true },
  { id:'checkout-reminder', name:'Checkout checklist', audience:'Guest', schedule:'Checkout day at 8:00 AM Eastern', trigger:'scheduled_checkout_day', exception:'Noon is used automatically when late checkout was purchased.', subject:'A quick Weeks Creek Haven checkout reminder', body:'Good morning {{guestName}},\n\nCheckout is {{checkout}} today. Please review the short checkout checklist in your cabin packet: {{packetUrl}}\n\nThank you for taking care of the Haven and spending your mountain time with us.', enabled:true, system:true },
  { id:'thank-you-review', name:'Thank-you and review follow-up', audience:'Guest', schedule:'One day after checkout at 10:00 AM Eastern', trigger:'scheduled_after_checkout', exception:'Skip if a review request was already sent or the stay was cancelled.', subject:'Thank you for staying at Weeks Creek Haven', body:'Hi {{guestName}},\n\nThank you for staying with us. We hope the cabin gave you a chance to slow down and enjoy Blue Ridge.\n\nWe would love your feedback: {{reviewUrl}}', enabled:true, system:true },
  { id:'return-referral-offer', name:'Return guest and referral offer', audience:'Guest', schedule:'Seven days after checkout at 10:00 AM Eastern', trigger:'scheduled_return_offer', exception:'Skip complimentary stays and guests who opted out; offers remain subject to owner approval.', subject:'Come back to Weeks Creek Haven', body:'Hi {{guestName}},\n\nWe would love to welcome you back. Request the returning-guest offer for 10% off an eligible future stay, or refer a new guest so both of you can request 10% savings. Offers do not stack and require approval.\n\nBook another stay: {{bookingUrl}}', enabled:true, system:true },
];

export function mergeEmailTemplates(overrides = []) {
  const byId = new Map(DEFAULT_EMAIL_TEMPLATES.map(item => [item.id, { ...item }]));
  for (const item of overrides) byId.set(item.id, { ...(byId.get(item.id) || {}), ...item });
  return [...byId.values()].filter(item => !item.deletedAt);
}

export function renderTemplate(value, variables = {}) {
  return String(value || '').replace(/\{\{([a-zA-Z0-9]+)\}\}/g, (_, key) => String(variables[key] ?? `{{${key}}}`));
}
